### ISSUE TITLE
Ida 7.2 x86 decompiler installer, fail pass find

### ISSUE THREAD

**Issue by Deltafox79** [namazso/ida_setup_password_cracker#1]
Hi I have try your code on :

x86_hexx86w_181105_9ea55cadb246b0159f404645bb45aa18.exe

> Compression=zip
> ; Encryption=yes
> ; PasswordHash=53e5e63cb55ccf591b1ecc5d34c72e559f52908a
> ; PasswordSalt=f78d0356f47737af

After change Hash and salt on ida_setup_password_cracker.c but hitout succes pass not find .. is normal?

**Comment by namazso** [comment]
somehow i didn't see this issue. anyways, HexRays fixed this sometime during 7.2 so some already have secure passwords. searching the net for the filename turns up sites without the password so this is most likely the case.
